language: node_js
node_js:
  - lts/*
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5433
    - TEST_DATABASE_URL=postgres://localhost:5433/travis
    - PGVERSION=10
cache:
  yarn: true
before_script:
  - git remote add deploy https://github.com/graphile/graphile.github.io.git
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - yarn clean
  - yarn build
  - yarn format
script:
  - scripts/ci
