language: node_js
node_js:
  - lts/*
addons:
  postgresql: "9.6"
env:
  TEST_DATABASE_URL: postgres://localhost:5432/travis
  PGVERSION: 9.6
cache:
  yarn: true
before_script:
  - git remote add deploy https://github.com/graphile/graphile.github.io.git
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - yarn clean
  - yarn build
  - yarn format
script:
  - scripts/ci
